---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkservices.networkservicemesh.io
spec:
  group: networkservicemesh.io
  version: v1
  scope: Cluster
  names:
    plural: networkservices
    singular: networkservice
    kind: NetworkService
    shortNames:
      - netsvc
      - netsvcs
  validation:
    properties:
      spec:
        properties:

